# Example rebase configuration file
# Copy this to .github/rebase-config.yml and modify as needed

# Base commit - the commit before the ones you want to modify
# Use: git log --oneline -10 to find the appropriate base commit
base_commit: "a1b2c3d4e5f6789012345678901234567890abcd"

# List of operations to perform on commits
operations:
  # Keep the first commit as-is
  - action: "pick"
    commit: "b2c3d4e5f6789012345678901234567890abcde"
  
  # Squash the second commit with a custom message
  - action: "squash"
    commit: "c3d4e5f6789012345678901234567890abcdef"
    message: |
      Implement user authentication feature
      
      This commit combines multiple changes:
      - Add OAuth2 integration with Google and GitHub
      - Implement session management with Redis backend
      - Add password strength validation
      - Include comprehensive unit and integration tests
      - Update API documentation
      
      Fixes #123, #124, #125
      
      Co-authored-by: Alice Developer <alice@company.com>
      Co-authored-by: Bob Tester <bob@company.com>
  
  # Squash additional commits without custom message (uses original)
  - action: "squash"
    commit: "d4e5f6789012345678901234567890abcdef01"