# Test workflow to verify custom token functionality
# This workflow demonstrates how to use the rebase workflow with a custom token

name: Test Custom Token Support

on:
  workflow_dispatch:
    inputs:
      test_mode:
        description: 'Test mode: default (uses GITHUB_TOKEN) or custom (uses REBASE_TOKEN)'
        required: true
        type: choice
        options:
          - default
          - custom

jobs:
  test-token-detection:
    name: Test Token Detection
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      
      - name: Test default token behavior
        if: inputs.test_mode == 'default'
        run: |
          echo "Testing default token behavior..."
          echo "This simulates the original workflow behavior"
          echo "Token would be: GITHUB_TOKEN"
          
          # Test the token fallback logic
          DEFAULT_TOKEN="${{ secrets.GITHUB_TOKEN }}"
          CUSTOM_TOKEN="${{ secrets.REBASE_TOKEN }}"
          SELECTED_TOKEN="${CUSTOM_TOKEN:-$DEFAULT_TOKEN}"
          
          if [ -z "$CUSTOM_TOKEN" ]; then
            echo "✅ REBASE_TOKEN not set, would use GITHUB_TOKEN (expected for default mode)"
          else
            echo "❌ REBASE_TOKEN is set but shouldn't be for default test"
          fi
      
      - name: Test custom token behavior
        if: inputs.test_mode == 'custom'
        run: |
          echo "Testing custom token behavior..."
          echo "This simulates when REBASE_TOKEN is available"
          
          # Test the token fallback logic
          DEFAULT_TOKEN="${{ secrets.GITHUB_TOKEN }}"
          CUSTOM_TOKEN="${{ secrets.REBASE_TOKEN }}"
          SELECTED_TOKEN="${CUSTOM_TOKEN:-$DEFAULT_TOKEN}"
          
          if [ -n "$CUSTOM_TOKEN" ]; then
            echo "✅ REBASE_TOKEN is set, would use custom token"
          else
            echo "⚠️  REBASE_TOKEN not set, would fall back to GITHUB_TOKEN"
            echo "   (This is expected if REBASE_TOKEN secret is not configured)"
          fi
  
  test-workflow-call:
    name: Test Workflow Call Interface
    runs-on: ubuntu-latest
    
    steps:
      - name: Validate workflow call syntax
        run: |
          echo "Testing that the workflow call interface is correct..."
          
          # Test the YAML structure we would use to call the rebase workflow
          cat << 'EOF' > test-workflow-call.yml
          jobs:
            test-rebase:
              uses: anatawa12/copilot-workspace/.github/workflows/rebase.yml@master
              with:
                branch: main
              secrets: inherit
          EOF
          
          # Validate YAML syntax
          python3 -c "import yaml; yaml.safe_load(open('test-workflow-call.yml')); print('✅ Workflow call YAML is valid')"
          
          echo "✅ Workflow call interface test passed"